### ISSUE TITLE
Services is not working if i give the name and description as mentioned in examples

### ISSUE THREAD

**Issue by vengateshcns** [xavierbriole/react-cookienotice#222]
<CookieNotice
      services={[
  {
    "name": "Necessary Cookies",
    "description": "Necessary cookies help make a website usable by enabling basic functions like page navigation and access to secure areas of the website. The website cannot function properly without these cookies.",
    "code": "NECESSARY",
    "alwaysActive": true
  },
  {
    "name": "Functional Cookies",
    "description": "Functional cookies enable a website to remember information that changes the way the website behaves or looks, like your preferred language or the region that you are in.",
    "code": "FUNCTIONAL"
  },
  {
    "name": "Performance Cookies",
    "description": "Performance cookies help website owners to understand how visitors interact with websites by collecting and reporting information anonymously.",
    "code": "PERFORMANCE"
  },
  {
    "name": "Marketing Cookies",
    "description": "Marketing cookies are used to track visitors across websites. The intention is to display ads that are relevant and engaging for the individual user and thereby more valuable for publishers and third party advertisers.",
    "code": "MARKETING"
  }
]}
    />

**Comment by xavierbriole** [comment]
Hello, thanks for the report. Can you please add some details about the error? Thanks.

Have a good day.

**Comment by xavierbriole** [comment]
Hello,

I think you're using the `latest` version (6.0.3) which don't have all the new functionalities described in the storybook.
If you want to use the storybook's examples, you need to upgrade to the `next` version (7.0.0-beta.3).

Because actually, the storybook documentation does not match the `latest` version but the last version published (which is `next` version). This storybook is not versioned. Maybe that's an improvement I have to care about in the future.

If you have any others problems, don't hesitate to create an other issue.
